### ISSUE TITLE
Add Color and Fonts 🎨

### ISSUE THREAD

**Issue by jatin2003** [jatin2003/resources-for-web-developers#3]
Hey @michael-andreuzza

It'll be great, If you can add [color and fonts](https://colorsandfonts.com) in the list too 😉

**Comment by jatin2003** [comment]
It's been added in the list & thanks for creating such an awesome resource 💖

**Comment by michael-andreuzza** [comment]
Hey Jatin,

That's very kind of you Thanks a lot man.
